import { Status } from "./permission.enum";

export enum AUTH_PERMISSIONS {
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_VIEW = "ROLE_VIEW",
  ROLE_DELETE = "ROLE_DELETE",

  DISCOUNT_CREATE = "DISCOUNT_CREATE",
  DISCOUNT_UPDATE = "DISCOUNT_UPDATE",
  DISCOUNT_VIEW = "DISCOUNT_VIEW",
  DISCOUNT_DELETE = "DISCOUNT_DELETE",

  HOTEL_CREATE = "HOTEL_CREATE",
  HOTEL_UPDATE = "HOTEL_UPDATE",
  HOTEL_VIEW = "HOTEL_VIEW",
  HOTEL_DELETE = "HOTEL_DELETE",

  PERMISSION_UPDATE = "PERMISSION_UPDATE",
  PERMISSION_VIEW = "PERMISSION_VIEW",
  PERMISSION_DELETE = "PERMISSION_DELETE",

  TOUR_CREATE = "TOUR_CREATE",
  TOUR_UPDATE = "TOUR_CREATE",
  TOUR_VIEW = "TOUR_VIEW",
  TOUR_DELETE = "TOUR_DELETE",
  TOUR_CANCEL = "TOUR_CANCEL",

  CUSTOMER_CREATE = "CUSTOMER_CREATE",
  CUSTOMER_UPDATE = "CUSTOMER_UPDATE",
  CUSTOMER_VIEW = "CUSTOMER_VIEW",
  CUSTOMER_DELETE = "CUSTOMER_DELETE",

  ROOM_CREATE = "ROOM_CREATE",
  ROOM_UPDATE = "ROOM_UPDATE",
  ROOM_VIEW = "ROOM_VIEW",
  ROOM_DELETE = "ROOM_DELETE",

  REVIEW_CREATE = "REVIEW_CREATE",

  BOOKING_CREATE = "BOOKING_CREATE",
  BOOKING_VIEW = "BOOKING_VIEW",
  BOOKING_CANCEL = "BOOKING_CANCEL",
  
  USER_VIEW = "USER_VIEW",

  REVIEW_GET = "REVIEW_GET",
  REVIEW_DELETE = "REVIEW_DELETE",
}

export enum USER_PERMISSIONS {
  HOTEL_VIEW = AUTH_PERMISSIONS.HOTEL_VIEW,
  DISCOUNT_VIEW = AUTH_PERMISSIONS.DISCOUNT_VIEW,
  TOUR_VIEW = AUTH_PERMISSIONS.TOUR_VIEW,
  BOOKING_CREATE = AUTH_PERMISSIONS.BOOKING_CREATE,
  BOOKING_CANCEL = AUTH_PERMISSIONS.BOOKING_CANCEL,
  BOOKING_VIEW = AUTH_PERMISSIONS.BOOKING_VIEW,
  CUSTOMER_UPDATE = AUTH_PERMISSIONS.CUSTOMER_UPDATE,
  USER_VIEW = AUTH_PERMISSIONS.USER_VIEW,
  ROOM_VIEW = AUTH_PERMISSIONS.ROOM_VIEW,
  REVIEW_CREATE = AUTH_PERMISSIONS.REVIEW_CREATE,
  REVIEW_GET = AUTH_PERMISSIONS.REVIEW_GET,
  REVIEW_DELETE = AUTH_PERMISSIONS.REVIEW_DELETE,
}

export const AUTH_ROLES = {
  ROLE: {
    ROLE_CREATE: Status.PUBLISHED,
    ROLE_UPDATE: Status.PUBLISHED,
    ROLE_VIEW: Status.PUBLISHED,
    ROLE_DELETE: Status.PUBLISHED,
  },
  DISCOUNT: {
    DISCOUNT_CREATE: Status.PUBLISHED,
    DISCOUNT_UPDATE: Status.PUBLISHED,
    DISCOUNT_VIEW: Status.PUBLISHED,
    DISCOUNT_DELETE: Status.PUBLISHED,
  },
  HOTEL: {
    HOTEL_CREATE: Status.PUBLISHED,
    HOTEL_UPDATE: Status.PUBLISHED,
    HOTEL_VIEW: Status.PUBLISHED,
    HOTEL_DELETE: Status.PUBLISHED,
  },
  PERMISSION: {
    PERMISSION_UPDATE: Status.PUBLISHED,
    PERMISSION_VIEW: Status.PUBLISHED,
    PERMISSION_DELETE: Status.PUBLISHED,
  },
  TOUR: {
    TOUR_CREATE: Status.PUBLISHED,
    TOUR_UPDATE: Status.PUBLISHED,
    TOUR_VIEW: Status.PUBLISHED,
    TOUR_DELETE: Status.PUBLISHED,
    TOUR_CANCEL: Status.PUBLISHED,
  },
  CUSTOMER: {
    CUSTOMER_CREATE: Status.PUBLISHED,
    CUSTOMER_UPDATE: Status.PUBLISHED,
    CUSTOMER_VIEW: Status.PUBLISHED,
    CUSTOMER_DELETE: Status.PUBLISHED,
  },
  ROOM: {
    ROOM_CREATE: Status.PUBLISHED,
    ROOM_UPDATE: Status.PUBLISHED,
    ROOM_VIEW: Status.PUBLISHED,
    ROOM_DELETE: Status.PUBLISHED,
  },
  BOOKING: {
    BOOKING_CREATE: Status.PUBLISHED,
    BOOKING_VIEW: Status.PUBLISHED,
    BOOKING_CANCEL: Status.PUBLISHED,
  },
  REVIEW: {
    REVIEW_CREATE: Status.PUBLISHED,
    REVIEW_GET: Status.PUBLISHED,
    REVIEW_DELETE: Status.PUBLISHED,
  },
  USER: {
    USER_VIEW: Status.PUBLISHED,
  }
};

export const AUTH_PERMISSION_META_KEY = "auth_permission_meta_key";
